// flow-typed signature: 4ce28c3f2af29b30f908dac9607afc30
// flow-typed version: <<STUB>>/eslint-plugin-jsdoc_v^50.6.1/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-jsdoc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-jsdoc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-jsdoc/eslint.config' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/alignTransform' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/defaultTagOrder' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/exportParser' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/getDefaultTagStructureForMode' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/getJsdocProcessorPlugin' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/iterateJsdoc' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/jsdocUtils' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/checkAccess' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/checkAlignment' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/checkExamples' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/checkIndentation' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/checkLineAlignment' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/checkParamNames' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/checkPropertyNames' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/checkSyntax' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/checkTagNames' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/checkTemplateNames' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/checkTypes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/checkValues' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/convertToJsdocComments' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/emptyTags' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/implementsOnClasses' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/importsAsDependencies' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/informativeDocs' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/linesBeforeBlock' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/matchDescription' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/matchName' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/multilineBlocks' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/noBadBlocks' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/noBlankBlockDescriptions' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/noBlankBlocks' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/noDefaults' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/noMissingSyntax' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/noMultiAsterisks' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/noRestrictedSyntax' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/noTypes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/noUndefinedTypes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/requireAsteriskPrefix' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/requireDescription' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/requireDescriptionCompleteSentence' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/requireExample' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/requireFileOverview' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/requireHyphenBeforeParamDescription' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/requireJsdoc' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/requireParam' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/requireParamDescription' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/requireParamName' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/requireParamType' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/requireProperty' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/requirePropertyDescription' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/requirePropertyName' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/requirePropertyType' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/requireReturns' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/requireReturnsCheck' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/requireReturnsDescription' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/requireReturnsType' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/requireTemplate' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/requireThrows' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/requireYields' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/requireYieldsCheck' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/sortTags' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/tagLines' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/textEscaping' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/rules/validTypes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/tagNames' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/utils/hasReturnValue' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jsdoc/src/WarnSettings' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-jsdoc/eslint.config.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/eslint.config'>;
}
declare module 'eslint-plugin-jsdoc/src/alignTransform.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/alignTransform'>;
}
declare module 'eslint-plugin-jsdoc/src/defaultTagOrder.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/defaultTagOrder'>;
}
declare module 'eslint-plugin-jsdoc/src/exportParser.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/exportParser'>;
}
declare module 'eslint-plugin-jsdoc/src/getDefaultTagStructureForMode.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/getDefaultTagStructureForMode'>;
}
declare module 'eslint-plugin-jsdoc/src/getJsdocProcessorPlugin.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/getJsdocProcessorPlugin'>;
}
declare module 'eslint-plugin-jsdoc/src/index' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src'>;
}
declare module 'eslint-plugin-jsdoc/src/index.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src'>;
}
declare module 'eslint-plugin-jsdoc/src/iterateJsdoc.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/iterateJsdoc'>;
}
declare module 'eslint-plugin-jsdoc/src/jsdocUtils.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/jsdocUtils'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/checkAccess.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/checkAccess'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/checkAlignment.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/checkAlignment'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/checkExamples.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/checkExamples'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/checkIndentation.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/checkIndentation'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/checkLineAlignment.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/checkLineAlignment'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/checkParamNames.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/checkParamNames'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/checkPropertyNames.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/checkPropertyNames'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/checkSyntax.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/checkSyntax'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/checkTagNames.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/checkTagNames'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/checkTemplateNames.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/checkTemplateNames'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/checkTypes.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/checkTypes'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/checkValues.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/checkValues'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/convertToJsdocComments.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/convertToJsdocComments'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/emptyTags.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/emptyTags'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/implementsOnClasses.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/implementsOnClasses'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/importsAsDependencies.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/importsAsDependencies'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/informativeDocs.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/informativeDocs'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/linesBeforeBlock.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/linesBeforeBlock'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/matchDescription.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/matchDescription'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/matchName.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/matchName'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/multilineBlocks.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/multilineBlocks'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/noBadBlocks.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/noBadBlocks'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/noBlankBlockDescriptions.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/noBlankBlockDescriptions'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/noBlankBlocks.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/noBlankBlocks'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/noDefaults.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/noDefaults'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/noMissingSyntax.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/noMissingSyntax'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/noMultiAsterisks.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/noMultiAsterisks'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/noRestrictedSyntax.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/noRestrictedSyntax'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/noTypes.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/noTypes'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/noUndefinedTypes.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/noUndefinedTypes'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/requireAsteriskPrefix.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/requireAsteriskPrefix'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/requireDescription.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/requireDescription'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/requireDescriptionCompleteSentence.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/requireDescriptionCompleteSentence'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/requireExample.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/requireExample'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/requireFileOverview.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/requireFileOverview'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/requireHyphenBeforeParamDescription.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/requireHyphenBeforeParamDescription'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/requireJsdoc.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/requireJsdoc'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/requireParam.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/requireParam'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/requireParamDescription.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/requireParamDescription'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/requireParamName.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/requireParamName'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/requireParamType.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/requireParamType'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/requireProperty.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/requireProperty'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/requirePropertyDescription.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/requirePropertyDescription'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/requirePropertyName.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/requirePropertyName'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/requirePropertyType.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/requirePropertyType'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/requireReturns.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/requireReturns'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/requireReturnsCheck.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/requireReturnsCheck'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/requireReturnsDescription.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/requireReturnsDescription'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/requireReturnsType.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/requireReturnsType'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/requireTemplate.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/requireTemplate'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/requireThrows.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/requireThrows'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/requireYields.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/requireYields'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/requireYieldsCheck.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/requireYieldsCheck'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/sortTags.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/sortTags'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/tagLines.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/tagLines'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/textEscaping.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/textEscaping'>;
}
declare module 'eslint-plugin-jsdoc/src/rules/validTypes.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/rules/validTypes'>;
}
declare module 'eslint-plugin-jsdoc/src/tagNames.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/tagNames'>;
}
declare module 'eslint-plugin-jsdoc/src/utils/hasReturnValue.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/utils/hasReturnValue'>;
}
declare module 'eslint-plugin-jsdoc/src/WarnSettings.js' {
  declare module.exports: $Exports<'eslint-plugin-jsdoc/src/WarnSettings'>;
}
