// flow-typed signature: 2bb3857674aa2cbce30961ee9771a0ba
// flow-typed version: <<STUB>>/husky_v^9.1.6/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'husky'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'husky' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'husky/bin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'husky/bin.js' {
  declare module.exports: $Exports<'husky/bin'>;
}
declare module 'husky/index' {
  declare module.exports: $Exports<'husky'>;
}
declare module 'husky/index.js' {
  declare module.exports: $Exports<'husky'>;
}
