// flow-typed signature: 8d70dd992339cd5962c3851bb3eca73b
// flow-typed version: <<STUB>>/stylelint_v^16.13.2/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint' {
  declare module.exports: any;
}
