// flow-typed signature: 0f5c06e1ff1d2c54e487c6cabc3e25e3
// flow-typed version: <<STUB>>/style-dictionary_v^4.1.4/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'style-dictionary'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'style-dictionary' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'style-dictionary/bin/style-dictionary' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/create-react-app/src/App' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/create-react-app/src/App.test' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/create-react-app/src/components/with-css-modules/ComponentWithCssModules' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/create-react-app/src/components/with-sass/ComponentWithSass' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/create-react-app/src/components/with-styled-components/ComponentWithStyledComponents' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/create-react-app/src' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/create-react-app/src/serviceWorker' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/create-react-native-app/__tests__/App' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/create-react-native-app/babel.config' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/create-react-native-app' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/create-react-native-app/metro.config' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/create-react-native-app/src/App' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/create-react-native-app/src/style-dictionary-dist/variables' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/custom-parser/sd.config' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/custom-transforms/build' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/font-face-rules/sd.config' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/format-helpers/sd.config' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/matching-build-files/config' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/matching-build-files/tokens' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/multi-brand-multi-platform/build' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/button/base' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/button' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/button/primary' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/button/secondary' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/config' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/background' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/border' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/brand' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/core' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/font' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/size/border' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/size/font' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/size' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/size/padding' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/s3/upload' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/tailwind-preset/config' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/tailwind-preset/config/filter' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/tailwind-preset/config/filter.test' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/tailwind-preset/config/format' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/tailwind-preset/config/transform' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/tailwind-preset/config/transform.test' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/tailwind-preset/tailwind.config' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/tokens-deprecation/build' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/tokens-deprecation/templates/ios-plist.template' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/tokens-deprecation/templates/web-scss.template' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/transitive-transforms/sd.config' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/variables-in-outputs/sd.config' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/yaml-tokens/sd.config' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/cleanActions' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/cleanDir' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/cleanDirs' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/cleanFile' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/cleanFiles' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/actions' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/filters' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/formatHelpers/createPropertyFormatter' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/formatHelpers/fileHeader' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/formatHelpers/formattedVariables' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/formatHelpers/getTypeScriptType' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/formatHelpers/iconsWithPrefix' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/formatHelpers' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/formatHelpers/minifyDictionary' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/formatHelpers/setComposeObjectProperties' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/formatHelpers/setSwiftFileProperties' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/formatHelpers/sortByName' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/formatHelpers/sortByReference' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/formats' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/templates/android/colors.template' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/templates/android/dimens.template' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/templates/android/fontDimens.template' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/templates/android/integers.template' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/templates/android/resources.template' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/templates/android/strings.template' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/templates/compose/object.kt.template' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/templates/css/fonts.css.template' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/templates/flutter/class.dart.template' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/templates/ios-swift/any.swift.template' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/templates/ios/colors.h.template' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/templates/ios/colors.m.template' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/templates/ios/macros.template' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/templates/ios/plist.template' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/templates/ios/singleton.h.template' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/templates/ios/singleton.m.template' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/templates/ios/static.h.template' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/templates/ios/static.m.template' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/templates/ios/strings.h.template' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/templates/ios/strings.m.template' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/templates/scss/map-deep.template' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/templates/scss/map-flat.template' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/templates/static-style-guide/index.html.template' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/transformGroups' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/transforms' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/enums/actions' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/enums/commentPositions' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/enums/commentStyles' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/enums/fileHeaderCommentStyles' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/enums/formats' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/enums' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/enums/logBrokenReferenceLevels' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/enums/logVerbosityLevels' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/enums/logWarningLevels' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/enums/propertyFormatNames' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/enums/transformGroups' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/enums/transforms' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/enums/transformTypes' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/filterTokens' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/fs-node' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/fs' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/performActions' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/Register' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/resolve' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/StyleDictionary' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/transform/config' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/transform/object' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/transform/token' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/transform/tokenSetup' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/cleanActions' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/combineJSON' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/convertToBase64' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/convertToDTCG' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/convertTokenData' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/createFormatArgs' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/deepExtend' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/deepmerge' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/detectDtcgSyntax' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/downloadFile' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/expandObjectTokens' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/flattenTokens' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/groupMessages' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/isNode' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/loadFile' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/preprocess' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/references/createReferenceRegex' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/references/defaults' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/references/getName' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/references/getPathFromName' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/references/getReferences' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/references/getValueByPath' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/references/outputReferencesFilter' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/references/outputReferencesTransformed' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/references/resolveReferences' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/references/usesReferences' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/resolveObject' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/stripMeta' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/typeDtcgDelegate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'style-dictionary/bin/style-dictionary.js' {
  declare module.exports: $Exports<'style-dictionary/bin/style-dictionary'>;
}
declare module 'style-dictionary/examples/advanced/create-react-app/src/App.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-app/src/App'>;
}
declare module 'style-dictionary/examples/advanced/create-react-app/src/App.test.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-app/src/App.test'>;
}
declare module 'style-dictionary/examples/advanced/create-react-app/src/components/with-css-modules/ComponentWithCssModules.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-app/src/components/with-css-modules/ComponentWithCssModules'>;
}
declare module 'style-dictionary/examples/advanced/create-react-app/src/components/with-sass/ComponentWithSass.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-app/src/components/with-sass/ComponentWithSass'>;
}
declare module 'style-dictionary/examples/advanced/create-react-app/src/components/with-styled-components/ComponentWithStyledComponents.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-app/src/components/with-styled-components/ComponentWithStyledComponents'>;
}
declare module 'style-dictionary/examples/advanced/create-react-app/src/index' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-app/src'>;
}
declare module 'style-dictionary/examples/advanced/create-react-app/src/index.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-app/src'>;
}
declare module 'style-dictionary/examples/advanced/create-react-app/src/serviceWorker.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-app/src/serviceWorker'>;
}
declare module 'style-dictionary/examples/advanced/create-react-native-app/__tests__/App.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-native-app/__tests__/App'>;
}
declare module 'style-dictionary/examples/advanced/create-react-native-app/babel.config.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-native-app/babel.config'>;
}
declare module 'style-dictionary/examples/advanced/create-react-native-app/index' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-native-app'>;
}
declare module 'style-dictionary/examples/advanced/create-react-native-app/index.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-native-app'>;
}
declare module 'style-dictionary/examples/advanced/create-react-native-app/metro.config.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-native-app/metro.config'>;
}
declare module 'style-dictionary/examples/advanced/create-react-native-app/src/App.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-native-app/src/App'>;
}
declare module 'style-dictionary/examples/advanced/create-react-native-app/src/style-dictionary-dist/variables.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-native-app/src/style-dictionary-dist/variables'>;
}
declare module 'style-dictionary/examples/advanced/custom-parser/sd.config.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/custom-parser/sd.config'>;
}
declare module 'style-dictionary/examples/advanced/custom-transforms/build.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/custom-transforms/build'>;
}
declare module 'style-dictionary/examples/advanced/font-face-rules/sd.config.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/font-face-rules/sd.config'>;
}
declare module 'style-dictionary/examples/advanced/format-helpers/sd.config.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/format-helpers/sd.config'>;
}
declare module 'style-dictionary/examples/advanced/matching-build-files/config.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/matching-build-files/config'>;
}
declare module 'style-dictionary/examples/advanced/matching-build-files/tokens/index' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/matching-build-files/tokens'>;
}
declare module 'style-dictionary/examples/advanced/matching-build-files/tokens/index.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/matching-build-files/tokens'>;
}
declare module 'style-dictionary/examples/advanced/multi-brand-multi-platform/build.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/multi-brand-multi-platform/build'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/button/base.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/button/base'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/button/index' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/button'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/button/index.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/button'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/button/primary.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/button/primary'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/button/secondary.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/button/secondary'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/index' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/index.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/config.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/config'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/background.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/background'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/border.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/border'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/brand.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/brand'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/core.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/core'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/font.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/font'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/index' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/index.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/index' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/index.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/size/border.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/size/border'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/size/font.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/size/font'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/size/index' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/size'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/size/index.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/size'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/size/padding.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/size/padding'>;
}
declare module 'style-dictionary/examples/advanced/s3/upload.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/s3/upload'>;
}
declare module 'style-dictionary/examples/advanced/tailwind-preset/config.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/tailwind-preset/config'>;
}
declare module 'style-dictionary/examples/advanced/tailwind-preset/config/filter.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/tailwind-preset/config/filter'>;
}
declare module 'style-dictionary/examples/advanced/tailwind-preset/config/filter.test.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/tailwind-preset/config/filter.test'>;
}
declare module 'style-dictionary/examples/advanced/tailwind-preset/config/format.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/tailwind-preset/config/format'>;
}
declare module 'style-dictionary/examples/advanced/tailwind-preset/config/transform.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/tailwind-preset/config/transform'>;
}
declare module 'style-dictionary/examples/advanced/tailwind-preset/config/transform.test.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/tailwind-preset/config/transform.test'>;
}
declare module 'style-dictionary/examples/advanced/tailwind-preset/tailwind.config.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/tailwind-preset/tailwind.config'>;
}
declare module 'style-dictionary/examples/advanced/tokens-deprecation/build.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/tokens-deprecation/build'>;
}
declare module 'style-dictionary/examples/advanced/tokens-deprecation/templates/ios-plist.template.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/tokens-deprecation/templates/ios-plist.template'>;
}
declare module 'style-dictionary/examples/advanced/tokens-deprecation/templates/web-scss.template.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/tokens-deprecation/templates/web-scss.template'>;
}
declare module 'style-dictionary/examples/advanced/transitive-transforms/sd.config.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/transitive-transforms/sd.config'>;
}
declare module 'style-dictionary/examples/advanced/variables-in-outputs/sd.config.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/variables-in-outputs/sd.config'>;
}
declare module 'style-dictionary/examples/advanced/yaml-tokens/sd.config.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/yaml-tokens/sd.config'>;
}
declare module 'style-dictionary/lib/cleanActions.js' {
  declare module.exports: $Exports<'style-dictionary/lib/cleanActions'>;
}
declare module 'style-dictionary/lib/cleanDir.js' {
  declare module.exports: $Exports<'style-dictionary/lib/cleanDir'>;
}
declare module 'style-dictionary/lib/cleanDirs.js' {
  declare module.exports: $Exports<'style-dictionary/lib/cleanDirs'>;
}
declare module 'style-dictionary/lib/cleanFile.js' {
  declare module.exports: $Exports<'style-dictionary/lib/cleanFile'>;
}
declare module 'style-dictionary/lib/cleanFiles.js' {
  declare module.exports: $Exports<'style-dictionary/lib/cleanFiles'>;
}
declare module 'style-dictionary/lib/common/actions.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/actions'>;
}
declare module 'style-dictionary/lib/common/filters.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/filters'>;
}
declare module 'style-dictionary/lib/common/formatHelpers/createPropertyFormatter.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/formatHelpers/createPropertyFormatter'>;
}
declare module 'style-dictionary/lib/common/formatHelpers/fileHeader.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/formatHelpers/fileHeader'>;
}
declare module 'style-dictionary/lib/common/formatHelpers/formattedVariables.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/formatHelpers/formattedVariables'>;
}
declare module 'style-dictionary/lib/common/formatHelpers/getTypeScriptType.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/formatHelpers/getTypeScriptType'>;
}
declare module 'style-dictionary/lib/common/formatHelpers/iconsWithPrefix.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/formatHelpers/iconsWithPrefix'>;
}
declare module 'style-dictionary/lib/common/formatHelpers/index' {
  declare module.exports: $Exports<'style-dictionary/lib/common/formatHelpers'>;
}
declare module 'style-dictionary/lib/common/formatHelpers/index.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/formatHelpers'>;
}
declare module 'style-dictionary/lib/common/formatHelpers/minifyDictionary.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/formatHelpers/minifyDictionary'>;
}
declare module 'style-dictionary/lib/common/formatHelpers/setComposeObjectProperties.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/formatHelpers/setComposeObjectProperties'>;
}
declare module 'style-dictionary/lib/common/formatHelpers/setSwiftFileProperties.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/formatHelpers/setSwiftFileProperties'>;
}
declare module 'style-dictionary/lib/common/formatHelpers/sortByName.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/formatHelpers/sortByName'>;
}
declare module 'style-dictionary/lib/common/formatHelpers/sortByReference.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/formatHelpers/sortByReference'>;
}
declare module 'style-dictionary/lib/common/formats.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/formats'>;
}
declare module 'style-dictionary/lib/common/templates/android/colors.template.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/templates/android/colors.template'>;
}
declare module 'style-dictionary/lib/common/templates/android/dimens.template.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/templates/android/dimens.template'>;
}
declare module 'style-dictionary/lib/common/templates/android/fontDimens.template.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/templates/android/fontDimens.template'>;
}
declare module 'style-dictionary/lib/common/templates/android/integers.template.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/templates/android/integers.template'>;
}
declare module 'style-dictionary/lib/common/templates/android/resources.template.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/templates/android/resources.template'>;
}
declare module 'style-dictionary/lib/common/templates/android/strings.template.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/templates/android/strings.template'>;
}
declare module 'style-dictionary/lib/common/templates/compose/object.kt.template.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/templates/compose/object.kt.template'>;
}
declare module 'style-dictionary/lib/common/templates/css/fonts.css.template.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/templates/css/fonts.css.template'>;
}
declare module 'style-dictionary/lib/common/templates/flutter/class.dart.template.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/templates/flutter/class.dart.template'>;
}
declare module 'style-dictionary/lib/common/templates/ios-swift/any.swift.template.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/templates/ios-swift/any.swift.template'>;
}
declare module 'style-dictionary/lib/common/templates/ios/colors.h.template.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/templates/ios/colors.h.template'>;
}
declare module 'style-dictionary/lib/common/templates/ios/colors.m.template.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/templates/ios/colors.m.template'>;
}
declare module 'style-dictionary/lib/common/templates/ios/macros.template.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/templates/ios/macros.template'>;
}
declare module 'style-dictionary/lib/common/templates/ios/plist.template.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/templates/ios/plist.template'>;
}
declare module 'style-dictionary/lib/common/templates/ios/singleton.h.template.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/templates/ios/singleton.h.template'>;
}
declare module 'style-dictionary/lib/common/templates/ios/singleton.m.template.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/templates/ios/singleton.m.template'>;
}
declare module 'style-dictionary/lib/common/templates/ios/static.h.template.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/templates/ios/static.h.template'>;
}
declare module 'style-dictionary/lib/common/templates/ios/static.m.template.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/templates/ios/static.m.template'>;
}
declare module 'style-dictionary/lib/common/templates/ios/strings.h.template.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/templates/ios/strings.h.template'>;
}
declare module 'style-dictionary/lib/common/templates/ios/strings.m.template.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/templates/ios/strings.m.template'>;
}
declare module 'style-dictionary/lib/common/templates/scss/map-deep.template.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/templates/scss/map-deep.template'>;
}
declare module 'style-dictionary/lib/common/templates/scss/map-flat.template.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/templates/scss/map-flat.template'>;
}
declare module 'style-dictionary/lib/common/templates/static-style-guide/index.html.template.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/templates/static-style-guide/index.html.template'>;
}
declare module 'style-dictionary/lib/common/transformGroups.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/transformGroups'>;
}
declare module 'style-dictionary/lib/common/transforms.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/transforms'>;
}
declare module 'style-dictionary/lib/enums/actions.js' {
  declare module.exports: $Exports<'style-dictionary/lib/enums/actions'>;
}
declare module 'style-dictionary/lib/enums/commentPositions.js' {
  declare module.exports: $Exports<'style-dictionary/lib/enums/commentPositions'>;
}
declare module 'style-dictionary/lib/enums/commentStyles.js' {
  declare module.exports: $Exports<'style-dictionary/lib/enums/commentStyles'>;
}
declare module 'style-dictionary/lib/enums/fileHeaderCommentStyles.js' {
  declare module.exports: $Exports<'style-dictionary/lib/enums/fileHeaderCommentStyles'>;
}
declare module 'style-dictionary/lib/enums/formats.js' {
  declare module.exports: $Exports<'style-dictionary/lib/enums/formats'>;
}
declare module 'style-dictionary/lib/enums/index' {
  declare module.exports: $Exports<'style-dictionary/lib/enums'>;
}
declare module 'style-dictionary/lib/enums/index.js' {
  declare module.exports: $Exports<'style-dictionary/lib/enums'>;
}
declare module 'style-dictionary/lib/enums/logBrokenReferenceLevels.js' {
  declare module.exports: $Exports<'style-dictionary/lib/enums/logBrokenReferenceLevels'>;
}
declare module 'style-dictionary/lib/enums/logVerbosityLevels.js' {
  declare module.exports: $Exports<'style-dictionary/lib/enums/logVerbosityLevels'>;
}
declare module 'style-dictionary/lib/enums/logWarningLevels.js' {
  declare module.exports: $Exports<'style-dictionary/lib/enums/logWarningLevels'>;
}
declare module 'style-dictionary/lib/enums/propertyFormatNames.js' {
  declare module.exports: $Exports<'style-dictionary/lib/enums/propertyFormatNames'>;
}
declare module 'style-dictionary/lib/enums/transformGroups.js' {
  declare module.exports: $Exports<'style-dictionary/lib/enums/transformGroups'>;
}
declare module 'style-dictionary/lib/enums/transforms.js' {
  declare module.exports: $Exports<'style-dictionary/lib/enums/transforms'>;
}
declare module 'style-dictionary/lib/enums/transformTypes.js' {
  declare module.exports: $Exports<'style-dictionary/lib/enums/transformTypes'>;
}
declare module 'style-dictionary/lib/filterTokens.js' {
  declare module.exports: $Exports<'style-dictionary/lib/filterTokens'>;
}
declare module 'style-dictionary/lib/fs-node.js' {
  declare module.exports: $Exports<'style-dictionary/lib/fs-node'>;
}
declare module 'style-dictionary/lib/fs.js' {
  declare module.exports: $Exports<'style-dictionary/lib/fs'>;
}
declare module 'style-dictionary/lib/performActions.js' {
  declare module.exports: $Exports<'style-dictionary/lib/performActions'>;
}
declare module 'style-dictionary/lib/Register.js' {
  declare module.exports: $Exports<'style-dictionary/lib/Register'>;
}
declare module 'style-dictionary/lib/resolve.js' {
  declare module.exports: $Exports<'style-dictionary/lib/resolve'>;
}
declare module 'style-dictionary/lib/StyleDictionary.js' {
  declare module.exports: $Exports<'style-dictionary/lib/StyleDictionary'>;
}
declare module 'style-dictionary/lib/transform/config.js' {
  declare module.exports: $Exports<'style-dictionary/lib/transform/config'>;
}
declare module 'style-dictionary/lib/transform/object.js' {
  declare module.exports: $Exports<'style-dictionary/lib/transform/object'>;
}
declare module 'style-dictionary/lib/transform/token.js' {
  declare module.exports: $Exports<'style-dictionary/lib/transform/token'>;
}
declare module 'style-dictionary/lib/transform/tokenSetup.js' {
  declare module.exports: $Exports<'style-dictionary/lib/transform/tokenSetup'>;
}
declare module 'style-dictionary/lib/utils/cleanActions.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/cleanActions'>;
}
declare module 'style-dictionary/lib/utils/combineJSON.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/combineJSON'>;
}
declare module 'style-dictionary/lib/utils/convertToBase64.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/convertToBase64'>;
}
declare module 'style-dictionary/lib/utils/convertToDTCG.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/convertToDTCG'>;
}
declare module 'style-dictionary/lib/utils/convertTokenData.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/convertTokenData'>;
}
declare module 'style-dictionary/lib/utils/createFormatArgs.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/createFormatArgs'>;
}
declare module 'style-dictionary/lib/utils/deepExtend.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/deepExtend'>;
}
declare module 'style-dictionary/lib/utils/deepmerge.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/deepmerge'>;
}
declare module 'style-dictionary/lib/utils/detectDtcgSyntax.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/detectDtcgSyntax'>;
}
declare module 'style-dictionary/lib/utils/downloadFile.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/downloadFile'>;
}
declare module 'style-dictionary/lib/utils/expandObjectTokens.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/expandObjectTokens'>;
}
declare module 'style-dictionary/lib/utils/flattenTokens.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/flattenTokens'>;
}
declare module 'style-dictionary/lib/utils/groupMessages.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/groupMessages'>;
}
declare module 'style-dictionary/lib/utils/index' {
  declare module.exports: $Exports<'style-dictionary/lib/utils'>;
}
declare module 'style-dictionary/lib/utils/index.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils'>;
}
declare module 'style-dictionary/lib/utils/isNode.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/isNode'>;
}
declare module 'style-dictionary/lib/utils/loadFile.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/loadFile'>;
}
declare module 'style-dictionary/lib/utils/preprocess.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/preprocess'>;
}
declare module 'style-dictionary/lib/utils/references/createReferenceRegex.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/references/createReferenceRegex'>;
}
declare module 'style-dictionary/lib/utils/references/defaults.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/references/defaults'>;
}
declare module 'style-dictionary/lib/utils/references/getName.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/references/getName'>;
}
declare module 'style-dictionary/lib/utils/references/getPathFromName.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/references/getPathFromName'>;
}
declare module 'style-dictionary/lib/utils/references/getReferences.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/references/getReferences'>;
}
declare module 'style-dictionary/lib/utils/references/getValueByPath.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/references/getValueByPath'>;
}
declare module 'style-dictionary/lib/utils/references/outputReferencesFilter.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/references/outputReferencesFilter'>;
}
declare module 'style-dictionary/lib/utils/references/outputReferencesTransformed.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/references/outputReferencesTransformed'>;
}
declare module 'style-dictionary/lib/utils/references/resolveReferences.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/references/resolveReferences'>;
}
declare module 'style-dictionary/lib/utils/references/usesReferences.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/references/usesReferences'>;
}
declare module 'style-dictionary/lib/utils/resolveObject.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/resolveObject'>;
}
declare module 'style-dictionary/lib/utils/stripMeta.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/stripMeta'>;
}
declare module 'style-dictionary/lib/utils/typeDtcgDelegate.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/typeDtcgDelegate'>;
}
