// flow-typed signature: 61b538676f1b2e8979393019ddd3508c
// flow-typed version: <<STUB>>/validate-branch-name_v^1.3.1/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'validate-branch-name'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'validate-branch-name' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'validate-branch-name/cli' {
  declare module.exports: any;
}

declare module 'validate-branch-name/config/config.default' {
  declare module.exports: any;
}

declare module 'validate-branch-name/lib/getConfig' {
  declare module.exports: any;
}

declare module 'validate-branch-name/lib/validateBranchName' {
  declare module.exports: any;
}

// Filename aliases
declare module 'validate-branch-name/cli.js' {
  declare module.exports: $Exports<'validate-branch-name/cli'>;
}
declare module 'validate-branch-name/config/config.default.js' {
  declare module.exports: $Exports<'validate-branch-name/config/config.default'>;
}
declare module 'validate-branch-name/index' {
  declare module.exports: $Exports<'validate-branch-name'>;
}
declare module 'validate-branch-name/index.js' {
  declare module.exports: $Exports<'validate-branch-name'>;
}
declare module 'validate-branch-name/lib/getConfig.js' {
  declare module.exports: $Exports<'validate-branch-name/lib/getConfig'>;
}
declare module 'validate-branch-name/lib/validateBranchName.js' {
  declare module.exports: $Exports<'validate-branch-name/lib/validateBranchName'>;
}
