// flow-typed signature: 626fe7f97c5c1428a07d0fcd47f924cf
// flow-typed version: <<STUB>>/vite-plugin-svgr_v^4.2.0/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vite-plugin-svgr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vite-plugin-svgr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vite-plugin-svgr/codemods/src/v4/default-export/default-export' {
  declare module.exports: any;
}

declare module 'vite-plugin-svgr/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vite-plugin-svgr/codemods/src/v4/default-export/default-export.js' {
  declare module.exports: $Exports<'vite-plugin-svgr/codemods/src/v4/default-export/default-export'>;
}
declare module 'vite-plugin-svgr/dist/index' {
  declare module.exports: $Exports<'vite-plugin-svgr/dist'>;
}
declare module 'vite-plugin-svgr/dist/index.js' {
  declare module.exports: $Exports<'vite-plugin-svgr/dist'>;
}
