// flow-typed signature: 572aae305d2fa5c2b941470d102566dd
// flow-typed version: <<STUB>>/vite-plugin-compression_v^0.5.1/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vite-plugin-compression'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vite-plugin-compression' {
  declare module.exports: any;
}
