// flow-typed signature: 9bf7c4d44269b0f9271c06dff5f3cea9
// flow-typed version: <<STUB>>/vite_v^6.0.7/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vite/bin/vite' {
  declare module.exports: any;
}

declare module 'vite/dist/node/chunks/dep-3RmXg9uo' {
  declare module.exports: any;
}

declare module 'vite/dist/node/chunks/dep-BJP6rrE_' {
  declare module.exports: any;
}

declare module 'vite/dist/node/chunks/dep-Cpceb51t' {
  declare module.exports: any;
}

declare module 'vite/dist/node/chunks/dep-DB1BmmOk' {
  declare module.exports: any;
}

declare module 'vite/dist/node/chunks/dep-DnSxfB-q' {
  declare module.exports: any;
}

declare module 'vite/dist/node/cli' {
  declare module.exports: any;
}

declare module 'vite/dist/node/constants' {
  declare module.exports: any;
}

declare module 'vite/dist/node' {
  declare module.exports: any;
}

declare module 'vite/dist/node/module-runner' {
  declare module.exports: any;
}

declare module 'vite/misc/false' {
  declare module.exports: any;
}

declare module 'vite/misc/true' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vite/bin/vite.js' {
  declare module.exports: $Exports<'vite/bin/vite'>;
}
declare module 'vite/dist/node/chunks/dep-3RmXg9uo.js' {
  declare module.exports: $Exports<'vite/dist/node/chunks/dep-3RmXg9uo'>;
}
declare module 'vite/dist/node/chunks/dep-BJP6rrE_.js' {
  declare module.exports: $Exports<'vite/dist/node/chunks/dep-BJP6rrE_'>;
}
declare module 'vite/dist/node/chunks/dep-Cpceb51t.js' {
  declare module.exports: $Exports<'vite/dist/node/chunks/dep-Cpceb51t'>;
}
declare module 'vite/dist/node/chunks/dep-DB1BmmOk.js' {
  declare module.exports: $Exports<'vite/dist/node/chunks/dep-DB1BmmOk'>;
}
declare module 'vite/dist/node/chunks/dep-DnSxfB-q.js' {
  declare module.exports: $Exports<'vite/dist/node/chunks/dep-DnSxfB-q'>;
}
declare module 'vite/dist/node/cli.js' {
  declare module.exports: $Exports<'vite/dist/node/cli'>;
}
declare module 'vite/dist/node/constants.js' {
  declare module.exports: $Exports<'vite/dist/node/constants'>;
}
declare module 'vite/dist/node/index' {
  declare module.exports: $Exports<'vite/dist/node'>;
}
declare module 'vite/dist/node/index.js' {
  declare module.exports: $Exports<'vite/dist/node'>;
}
declare module 'vite/dist/node/module-runner.js' {
  declare module.exports: $Exports<'vite/dist/node/module-runner'>;
}
declare module 'vite/misc/false.js' {
  declare module.exports: $Exports<'vite/misc/false'>;
}
declare module 'vite/misc/true.js' {
  declare module.exports: $Exports<'vite/misc/true'>;
}
