// flow-typed signature: f9006d5ba2902171e4a28b393a548eec
// flow-typed version: <<STUB>>/@rollup/plugin-terser_v^0.4.4/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@rollup/plugin-terser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@rollup/plugin-terser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@rollup/plugin-terser/dist/cjs' {
  declare module.exports: any;
}

declare module '@rollup/plugin-terser/dist/es' {
  declare module.exports: any;
}

// Filename aliases
declare module '@rollup/plugin-terser/dist/cjs/index' {
  declare module.exports: $Exports<'@rollup/plugin-terser/dist/cjs'>;
}
declare module '@rollup/plugin-terser/dist/cjs/index.js' {
  declare module.exports: $Exports<'@rollup/plugin-terser/dist/cjs'>;
}
declare module '@rollup/plugin-terser/dist/es/index' {
  declare module.exports: $Exports<'@rollup/plugin-terser/dist/es'>;
}
declare module '@rollup/plugin-terser/dist/es/index.js' {
  declare module.exports: $Exports<'@rollup/plugin-terser/dist/es'>;
}
