// flow-typed signature: e0e70ef2b5c69e2a19e0b4f4fcdc44b7
// flow-typed version: <<STUB>>/@storybook/react-vite_v^8.3.6/flow_v0.259.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/react-vite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/react-vite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/react-vite/dist' {
  declare module.exports: any;
}

declare module '@storybook/react-vite/dist/preset' {
  declare module.exports: any;
}

declare module '@storybook/react-vite/preset' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/react-vite/dist/index' {
  declare module.exports: $Exports<'@storybook/react-vite/dist'>;
}
declare module '@storybook/react-vite/dist/index.js' {
  declare module.exports: $Exports<'@storybook/react-vite/dist'>;
}
declare module '@storybook/react-vite/dist/preset.js' {
  declare module.exports: $Exports<'@storybook/react-vite/dist/preset'>;
}
declare module '@storybook/react-vite/preset.js' {
  declare module.exports: $Exports<'@storybook/react-vite/preset'>;
}
